### ISSUE TITLE
Site quebrando no mobile

### ISSUE THREAD

**Issue by daniellucasdev** [ArtuTerra/lista_tarefas#1]
Ola amigo, na resoluçao de 400px o site fica com o background quebrado, arrumar isso me ajudaria muito.

**Comment by ArtuTerra** [comment]
Olá colega, _atualizei o site!_ Agora o background funciona em telas de menos de 400px de largura. Somente abaixo de 70px ele começa a quebrar.

Espero que isso lhe ajude e obrigado pelo feedback!
